modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/onVoid/RottenLeather/issues"


[[mods]]
modId="rottenleather"
version="${file.jarVersion}"
displayName="Rotten Leather"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rotten-leather"
updateJSONURL="https://onvoid.net/rottenleather/update.json"
logoFile="rottenleather.png"
logoBlur=false
credits="onVoid"
authors="onVoid"
description="Adds a way to convert Rotten Flesh into Leather or food."
itemIcon="rottenleather:rotten_chunk"
configBackground="minecraft:textures/block/stone.png"

[[dependencies.coppersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"